### ISSUE TITLE
Поддержка Linux

### ISSUE THREAD

**Issue by LevkinSergey** [Pr-Mex/VAEditor#102]
Добрый день!
Планируется ли сделать поддержку работы с linux? 

Сейчас при открытии редактора в форме 1С просто вылетает.

**Comment by zeegin** [comment]
Нужно больше информации о проблеме.
Какая платформа.
Какой линукс.
Дамп если есть.
Техжурнал если есть.

**Comment by LevkinSergey** [comment]
linux mint 20
платформу пробовал 
8.3.14.1694- не загружается. выдает ошибку
8.3.15.1700,1778, 8.3.16.1359, 8.3.17.1386 - вылетает

дампа нет. 

Техножурнал чуть позже пришлю

**Comment by zeegin** [comment]
Скриншот, хоть какие-то логи, попробуй открыть консоль (фокус на HTML документ и хоткей `Ctrl+Shift+Alt+F12`) и пришли что есть в консоли.

**Comment by LevkinSergey** [comment]
Видимо это сочетание клавиш для винды. Там консоль открывается(отдельное спасибо, что показали ее существование. Очень не хватало).
А в линухе система глохнет. Где можно про горячие клавиши посмотреть, чтобы просвятиться и прислать нужную инфу?

**Comment by zeegin** [comment]
В вин и маке все ок. В Линуксе проблема воспроизвелась.
Пока не понятно в чем проблема.

**Comment by LevkinSergey** [comment]
получилось вызвать инспектор в линуксе. Оказывается нужно правый ctrl и alt зажимать

**Comment by salexdv** [comment]
Столкнулся с похожей проблемой в bsl_console. Похоже, что проблема в версии EcmaScript
![bsl_console_linux](https://user-images.githubusercontent.com/6356534/88157107-00516280-cc13-11ea-9b55-b87b65ef2813.png)

**Comment by salexdv** [comment]
> Столкнулся с похожей проблемой в bsl_console. Похоже, что проблема в версии EcmaScript
Прогнал через babel и частично заработало.

**Comment by zeegin** [comment]
babel такой же транспиляцией занимается как и typescript можно просто конфиг tsconfig поправить
надо попробовать таргет выбрать es5

**Comment by salexdv** [comment]
> babel такой же транспиляцией занимается как и typescript можно просто конфиг tsconfig поправить
> надо попробовать таргет выбрать es5

Это понятно, просто у меня чистый JS используется, поэтому и babel. Думаю, что проблема как раз в этом, видимо что libwebkitgtk-3.0-0 только es5 умеет.

**Comment by lintest** [comment]
> So I've got it working by compiling my typescript using the 'commonJs' module system targetting 'es6'. I then use webpack together with the monaco-editor-webpack-plugin and babel-loader to transpile my generated JS to es5 which produces a bundle which I can load in my HTML page. I now have the editor loaded and working.
> 
> Hope this helps someone else who is stuck getting started:
> 
> https://github.com/Microsoft/monaco-editor/issues/1279#issuecomment-459075371

**Comment by lintest** [comment]
Статьи по теме WebPack:

* [Введение в Webpack для новичков](https://medium.com/nuances-of-programming/%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-webpack-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%BE%D0%B2%D0%B8%D1%87%D0%BA%D0%BE%D0%B2-6cafbf562386)

* [Разбираемся с настройкой Webpack для любого проекта](https://webdevblog.ru/razbiraemsya-s-nastrojkoj-webpack-dlya-ljubogo-proekta/)

* [Настройка Webpack 5 с нуля](https://m.habr.com/ru/post/524260/)
