### ISSUE TITLE
Как по нажатию клавиши "." наполнить, отобразить и обработать выбор списка автодополнения?

### ISSUE THREAD

**Issue by tormozit** [Pr-Mex/VAEditor#107]
Как в коде 1С по нажатию клавиши "." наполнить, отобразить и обработать выбор списка автодополнения?

**Comment by lintest** [comment]
Для этого нужно зарегистрировать провайдера: registerCompletionItemProvider

https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registercompletionitemprovider
