### ISSUE TITLE
Сделать настройку и метод для нормализации табуляторов, пробелов в документе.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/VAEditor#113]

**Comment by Pr-Mex** [comment]
Аналог в VSCode.
![image](https://user-images.githubusercontent.com/8627416/91186129-54120880-e6f7-11ea-9cbc-01e474148be7.png)

**Comment by lintest** [comment]
Также количество пробелов для табуляторов.

**Comment by lintest** [comment]
Настройка сделана, осталось сделать метод ля нормализации. Для этого можно использовать: [normalizeIndentation](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html)

**Comment by lintest** [comment]
![image](https://user-images.githubusercontent.com/92895/91595957-10c0cf80-e96d-11ea-92fa-30cb4c8de92e.png)
