### ISSUE TITLE
Добавить опцию выключения синтаксического контроля

### ISSUE THREAD

**Issue by andrewzola** [Pr-Mex/VAEditor#127]
Когда аналитик начинает работать со сценарием, он в общем случае сначала вообще не использует шаги. Он фиксирует сценарии фичи и затем детализирует сценарии верхнеуровневыми шагами (группами в вашей терминологии).

очень упрощенный пример
Сценарий: Оформление продажи товара
  Когда Я открываю документ продажи
  И заполняю условия продажи
  И заполняю товары с ценами и количеством
  Тогда я могу оформить продажу

Все эти строки будут помечены как ошибка, а если их оформить как группы, тогда не будут подсвечиваться ключевые слова.

Вот так с включенной подсказкой
![image](https://user-images.githubusercontent.com/37068126/104737523-68fa4180-5755-11eb-9092-a8e56294cc3f.png)

Вот так с выключенной подсказкой
![image](https://user-images.githubusercontent.com/37068126/104737466-52ec8100-5755-11eb-9c3f-04e9ae8ba9ce.png)

**Comment by lintest** [comment]
Эта настройка должна действовать только для текущей вкладки редактора или на все вкладки?

**Comment by Pr-Mex** [comment]
@lintest 
Думаю на все вкладки. Это что-то глобальное.

**Comment by lintest** [comment]
```js
VanessaTabs.enableSyntaxCheck = false;
```
