### ISSUE TITLE
Запретите какую либо команду или почините работу клика по колёсику мыши.

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/VAEditor#140]
Сейчас, при клике на колёскио мыши (то, как это реализовано во многих продуктах) - должна закрываться вкладка. Так работает в 1с предприятие с закладками - если открыт какой-то справочник\документ\регистр сведений.... Или chrome\mozilla.
В VAeditor если нажать эу клавишу - включается "перемещение по странице". И эта страница длиной и шириной - с размер полоски с вкладками открытых фич. Если её нажать на колёсико мыши и перевести мышь вниз - прекращает быть видно вся панель с открытыми сценариями. Возвращается панель с открытием\повторным кликом на какую-то фичу из дерева или при "игрой" с масштабом текста.
Ожидается, что при клике по кнопке на колёсике - вкладка открытого сценария - закроется.

![d9gHK4fr12](https://user-images.githubusercontent.com/45041332/144404669-4c8e4728-861c-4518-9493-8b9218d501d0.gif)

**Comment by Pr-Mex** [comment]
@lintest 
Ты можешь повторить поведение при клике на кнопку колеса мышки?
