### ISSUE TITLE
Выделение красным некоторых лексем

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/VAEditor#145]
Нужно, чтобы 
#Если
и
#КонецЕсли
и выделялись красным цветом, если это нужно.
Сейчас они выделаются зеленым как обычные комментарии
Нужен метод, который бы переключил это поведение и такие строки больше бы не считались комментариями.

**Comment by Pr-Mex** [comment]
Если в строк  в начале написано 
#Если или #КонецЕсли, то не  важно что дальше. Эти строки не считаются комментариями в таком новом режиме.
Между словом и # не должно быть пробелов.

**Comment by lintest** [comment]
![image](https://user-images.githubusercontent.com/92895/209481113-e0aad02d-509c-46ff-baa6-2389687afb20.png)

**Comment by lintest** [comment]
```bsl
&AtClient
Function GetDirectives()

	words = "
		|#Если
		|#ИначеЕсли
		|#Иначе
		|#КонецЕсли
		|";

	split = "
	|";

	Directives = StrSplit(words, split, False);

	Return JsonDump(Directives);

EndFunction

GherkinProvider.setDirectives(GetDirectives());
```

**Comment by Pr-Mex** [comment]
@lintest 
Можно сделать, чтобы красным выделились только указанные в методе слова (#Если, #КонецЕсли)?
А то сейчас красным стали все лексемы
![image](https://user-images.githubusercontent.com/8627416/209969194-12e04dca-6df8-4e15-bac3-53a448e3f82e.png)

**Comment by Pr-Mex** [comment]
Решено.
